### ISSUE TITLE
[Feature request] Reset bank state on close

### ISSUE THREAD

**Issue by mheine** [dillydill123/inventory-setups#108]
Massive thanks for this plugin, it's been immensely helpful in trying to sort out my setups!

A feature I (personally) would like to see would be that suppose you filter the bank by a setup, and then close and re-open the bank, it would be reset to the "original" bank state.

This would probably also come with a `config` option for this behavior that defaults to `false`, since I assume my preference might not apply to everyone.

I took a quick look in `src/main/java/inventorysetups/InventorySetupsPlugin.java` but couldn't get a good overview of where this would be added - but could give coding it myself a go if you point me in the right direction. Cheers, and thanks again!

**Comment by dillydill123** [comment]
Hey. Thanks for the kind words, and sorry about the code being difficult to follow. If I had read Uncle Bob's clean code before I started this plugin rather than after, it may have faired better 😆 there are definitely some design decisions I regret.

I think the feature you want has an easy solution. I think the simplest way is to only allow the filter to occur if the bank widget is already loaded. So what this means is that when the bank widget loads, we check to see if the config option is selected. If so, we disallow any filtering when the bank is opened. However, selecting a setup (or using a hot key) will automatically allow filtering to occur. So we can still do a 1 one time filter if we manually provoke it the bank when it is already open.

So to implement this feature, add the config option, and in `onWidgetLoaded` in `InventorySetupsPlugin.java` add a check for the new config option to avoid setting `internalFilteringIsAllowed` to true. This should stop the bank filter from happening at all when the bank is opened. It would mean that you have to manually provoke the bank filter by selecting the setup or pressing the hotkey **when the bank is already open**. If you want to give this a shot, feel free. Else I can try to implement it.

**Comment by dillydill123** [comment]
I've implemented the feature and it's working as I described. It had a few more things to find (the nav button specifically). It will be in the next update. I'll close the ticket when it's officially out.

**Comment by mheine** [comment]
Much appreciated, and thanks for getting to it so quickly!

**Comment by dillydill123** [comment]
Available now in v1.12

**Comment by mheine** [comment]
King :crown: :100: :
