### ISSUE TITLE
The ability to categorize setups

### ISSUE THREAD

**Issue by T7000** [dillydill123/inventory-setups#13]
After a dozen or more entries & having to scroll through them it becomes a difficult to quickly find what I'm looking for.

I think the ability to list entries in categories and divided by headers could make it easier to find individual ones.

**Comment by dillydill123** [comment]
This is an interesting idea. This has some good potential. You could easily hide categories with a button as well

**Comment by dillydill123** [comment]
I'm thinking this will not be needed because the search bar can alleviate what this is trying to fix. You can also create your own "pseudo" categories by adding a prefix to your setups. E.g., "Slayer - <creature>" This would mean if you search "Slayer" you'll get all your slayer related setups. I'll leave this open for now and consider it some more.

**Comment by dillydill123** [comment]
Closing unless I change my mind and want to add something like this
