### ISSUE TITLE
Sort bank equipment button right-click list 

### ISSUE THREAD

**Issue by DrJam** [dillydill123/inventory-setups#144]
Would it be possible to sort the right-click menu to match the sorting order of the plugin menu?

![RuneLite_2022-07-12_07-51-27](https://user-images.githubusercontent.com/3051130/178427384-5977250c-5560-462c-a9a0-995a705675b3.png)

**Comment by dillydill123** [comment]
Yep this is something I definitely should have done a long time ago. But I wanted to refactor that list to potentially fix the issue where there are too many setups.

**Comment by jeffreyjhaywood** [comment]
For a quicker fix while you work on the refactor, can I add the option to sort the worn equipment list to be sorted alphabetically?

I was thinking to add a right click option to the sorting icon in the plugin menu. That menu will contain a button when pressed will sort the list that contains the setups that are displayed there alphabetically.

**Comment by jeffreyjhaywood** [comment]
Was able to get something working.

I wound up adding an option in the plugin config menu instead of what I initially proposed.

Unordered (What my menu currently looks like)
![UnorderedEquipment](https://user-images.githubusercontent.com/33064835/207642374-f6fe9740-b1ef-407e-8402-f95f2c3ab861.png)

Ordered Alphabetically:
![AlphabeticalWornEquipment](https://user-images.githubusercontent.com/33064835/207642735-b41bd588-b2b2-40a3-8db0-bd6af11e1d77.png)

Going to clean up a few things and submit a pr

**Comment by rigadoog** [comment]
> Was able to get something working.

Hey, I'd like to use this version of the plugin that you've created but I'm not sure how.

**Comment by dillydill123** [comment]
@jeffreyjhaywood Feel free to make a pull request or if you wanna show me the implementation I can take a look at it. Sorry for the delayed response

**Comment by dillydill123** [comment]
It's matching the side panel now
