### ISSUE TITLE
A button to re-filter bank

### ISSUE THREAD

**Issue by T7000** [dillydill123/inventory-setups#16]
When I exit the filtered bank by opening another tab I miss a button in the panel to filter the bank again. Right now I have to close/open the bank or the setup to get the filter back.

**Comment by dillydill123** [comment]
Yeah I’ve come across this myself. Also I hate accidentally clicking on the tab # when the bank is filtered so having a hot key to refilter the bank is a good idea. Will be really easy to add too.

**Comment by dillydill123** [comment]
Added the hot key. It was actually a little more troublesome than i originally expected. Basically you have to wait at least one game tick before allow the filtering to reoccur, otherwise the filtering would happen but if you had selected a tab previously, it would go back to that tab. I was still able to get this to occur, but only after hitting the hot key button extremely fast after clicking a different tab.

I was able to avoid this by making the client wait two ticks before filtering. But now that means the user would have to wait up to 1.2 seconds just to see the bank filtered. For how rare the previously mentioned issued occurred, I decided to just wait one game tick. If it is a problem later down the road I can try increasing the wait time using cycles or figure out another solution entirely.
