### ISSUE TITLE
Minor bug when changing between Item/Note Withdrawal methods

### ISSUE THREAD

**Issue by PortalInTime** [dillydill123/inventory-setups#170]
It's a very small thing, but I just discovered that going between "Withdraw as Item" and "Withdraw as Note" while an inventory setup is open causes a weird bug where the setup is overlaid on the bank tab you were on prior to opening the setup.
![image](https://user-images.githubusercontent.com/42799619/197674210-91218da1-5c03-4db2-8014-8f5d523ee578.png)

Here's a before and after. It can be fixed with the right click menu to open up more setups, so it's not overly game-breaking, but I thought I'd bring it up! Thanks for making (and maintaining) a great plugin like this :)

**Comment by dillydill123** [comment]
This is a bug due to having bank tags on, unfortunately nothing can be done about it. See the bank tag s section on the tutorial here https://github.com/dillydill123/inventory-setups#bank-tags-plugin for more info. You also have bank tag layouts on so that is why you also get a strange behavior. Normally it just cancels the filter
