### ISSUE TITLE
Setups are not saving

### ISSUE THREAD

**Issue by NoNick96** [dillydill123/inventory-setups#179]
Hello. I've used the pluging a while ago and now I've redownloaded it, but any setup I'm trying to create is not saving. Every time i close and reopen Runelite the setups are gone. I have a setup created called "Melee" but it was so long ago that i don't even remember creating it. If I delete it it appears back after relaunching Runelite. I've tried removing the contents of "inventorysetups.setups" line in my profile's settings.properties file, but the string comes back after launching Runelite.

**Comment by dillydill123** [comment]
I've already fixed this bug but I haven't pushed the update yet. There's a fix you can do in the meanwhile. The reason the string returns is because it's fetching it from your cloud profile.

So you need to copy your settings to your local profile. Which is just the settings.properties in the .runelite folder
. Delete the line, then log back into your RuneLite profile and import from local settings. Wait 5 minutes for settings to sync then close the client.
