### ISSUE TITLE
Worn graceful doesn't show up in bank filtering

### ISSUE THREAD

**Issue by asherbasher** [dillydill123/inventory-setups#19]
I've tried on two different accounts; one with regular graceful and one with recoloured graceful and neither of them show when filtering the bank. This only happens when the graceful is part of your worn equipment in the inventory setup (which it would be in 99% of cases), but not when it's part of the regular inventory.

**Comment by asherbasher** [comment]
![1tg9zR2](https://user-images.githubusercontent.com/10160470/74676807-bf11de00-51ae-11ea-8b77-c66e01933dcc.png)

**Comment by dillydill123** [comment]
Thanks for finding this. I think this is occurring because equipment that reduces weight has a different itemID than when it’s just in the inventory. So it’s basically comparing two different IDs which is why the filter doesn’t work. Do you have the Variation Difference enabled?

**Comment by asherbasher** [comment]
Yeah I do. It does indeed show correctly if I turn that off.

**Comment by dillydill123** [comment]
So this problem is a tough one to fix because there isn't a set list of items that have different item IDs when worn (basically all weight reducing items). I could make such a list but then I would have to find all items with this property and maintain the list which will change frequently (black graceful is probably the next thing to be added). So instead of doing this, here is another solution that will be 95% correct and much cleaner to implement:

When filtering the bank, all **equipped items** will have variation mapping **off**. This will make it so that graceful and other weird items like this will properly show up in the bank. The trade off is that Rings and amulets off different charges will also show up if you have variation mapping enabled. I think this tradeoff is worth it because I'd rather have a few other rings or amulets potentially show up than my graceful not showing up at all. Again, this is only for equipped items so it wouldn't affect inventory items.

What do you think of this change?

**Comment by asherbasher** [comment]
That sounds like a fair trade off to me.

**Comment by dillydill123** [comment]
Fixed was merged into the plugin hub so it should be in soon.
