### ISSUE TITLE
Salve (e) in bank filtering

### ISSUE THREAD

**Issue by AnkouOSRS** [dillydill123/inventory-setups#21]
Fairly minor but the Salve amulet (e) shows up in the filtered bank when Salve amulet (ei) is part of the setup.

**Comment by asherbasher** [comment]
If you turn on "Enable highlighting for variation differences" it shouldn't.

**Comment by dillydill123** [comment]
Actually, I think with the bug fix for graceful not showing up in the filter, this will happen now. Again, this is difficult to solve because there isn’t a good solution for getting the graceful to show up without variation difference being turned off for equipped items. Maybe I can think of another solution.

**Comment by dillydill123** [comment]
Turns out there was an API for this all along in the ItemManager::canonicalize method. Not sure how I didn't notice because I'm using this function in some spots... it automatically converts bank note ids, placeholders, and **worn items** to the "normal" id. So this will solve this bug and the graceful one as well.... Hopefully it doesn't introduce any new ones
