### ISSUE TITLE
Clue Scrolls filter all tiers when fuzzy

### ISSUE THREAD

**Issue by Raitab** [dillydill123/inventory-setups#216]
Marking a clue scroll in a setup as fuzzy causes all types of clue scrolls to be recognized. If, for instance, I have a "Hard Clue Scrolls" setup, I don't want Beginner, Easy, Mediums, Elites, or Masters in my setup, but they'll show up. Clue scrolls in setups _have_ to be fuzzy to be useful, and this behavior isn't ideal for me. If I mark a hard clue as fuzzy, I'd love for only hard clues to be included.

**Comment by Nightfirecat** [comment]
I think that's a feature of RuneLite, not of this plugin; our item variations currently reports all clue scrolls as a single variant of `"Clue scroll"`, because [the item variation updater strips all text within parentheses](https://github.com/abextm/runelite-cache-code-updater/blob/aa2ee80c9beea5e9b053cef9705e3f6a68df0bea/src/main/java/net/runelite/cache/codeupdater/apifiles/ItemVariationsUpdate.java#L49). I don't know that we'd want to change how this works at a client level, as there are likely some existing use cases where players have tagged clue scrolls and would want all tiers of clues to be affected.

**Comment by Raitab** [comment]
I think that it would make sense as a toggle, but I believe it makes less sense to keep it as-is. If people want multiple tiers of clue scrolls, they can add the tiers individually, if they only want one, they _can't_. Is it possible for Fuzzy to work custom-made in-plugin specifically for Clue Scrolls?

**Comment by dillydill123** [comment]
I've noticed this before but as I am using the item variation API from RuneLite I'd prefer not to deviate from that. It's easy to add more variations, but it's difficult to ones made by RL. Sorry for the inconvenience
