### ISSUE TITLE
Swapping between "item" and "note" in bank exits filtered setup

### ISSUE THREAD

**Issue by asherbasher** [dillydill123/inventory-setups#22]
Sorry if the title is poorly worded, wasn't sure exactly how to describe it.

If you click to view one of your inventory setups with the filtering mode enabled and then switch between "item" and "note", the filtering will exit and you'll be back inside the bank tab you were previously in before viewing the setup.

This issue does _not_ occur if you were in the main bank tab ("view all items") beforehand, only if you're in one of the other bank tabs. This fact makes it an easy workaround, just don't be in any other tab before viewing a setup, but I still figured it's a bug nonetheless.

**Comment by dillydill123** [comment]
What a strange bug. Could you test and see if this happens with bank tags? Perhaps they have a solution for this.

**Comment by asherbasher** [comment]
It does not happen with bank tags.

**Comment by dillydill123** [comment]
So the fix is the same that the bank tag uses... The only problem with this is that if you have bank tags and inventory setups turned on at the same time, clicking note or item will always cause an exit for the filtered setup. 

This is because bank tags will check if a bank tag is selected when those buttons are clicked. If a bank tag is selected, it won't exit. Now Inventory Setups does the same thing except for inventory setups. The problem is that you can't have a bank tag and an inventory setup selected, so one of them is going to cause the filter to exit when the item or note button is clicked.

To stop this from happening, bank tags or inventory setups must be turned off. I'm not sure if there is a better fix. This is because there's no way for bank tags to communicate with inventory setups. It will always be the case that having bank tags and inventory setups on will cause the filter to exit when inventory setups is filtering. There may be a way I can stop it from exiting when a bank tag is selected, but I don't see a solution now.

Without this fix, the filter would exit even if bank tags are turned off, so I think it is necessary.

**Comment by dillydill123** [comment]
The fix is a little more complicated than I thought. I've tried breaking it but it looks like it works for me. Let me know if you have any weird behavior with the bank and buttons. Thanks for all the help 👍
