### ISSUE TITLE
Select/View setup from in-game, without the panel

### ISSUE THREAD

**Issue by Matsyir** [dillydill123/inventory-setups#25]
As someone who mostly plays in fixed, with the panel closed, I think it would be great if we could select an inventory setup from the game without using the panel (for bank filtering). Similar to how bank tags has tabs, although it doesn't need to be that 'fancy'. One way could be to show the setup in searches if you search `inv:TAG_NAME`. Another way I thought of that would be nice (until you have too many setups), is adding menu entries to the show worn items button:
![image](https://user-images.githubusercontent.com/28902643/79144707-65342b80-7d8d-11ea-9e1f-6d791883dd45.png)
So, it would just list all your inventory setup names and clicking it would filter the bank based on that setup.
Not sure what kind of limitations there are for adding to those menus, but a lot of plugins seem to do it without issues.

I'm willing to implement this myself if you'd like, not sure if anything like this was in the works, let me know what you think.

**Comment by dillydill123** [comment]
Hey, thanks for the suggestion. I think it's a nice feature to have. Here are my thoughts:

I agree that it doesn't need to be as 'fancy' as bank tags. In fact, I wouldn't want to recreate what bank tags does because it would cause further incompatibility with bank tags. It's also a lot of difficult (and probably tedious) interface work. That being said, if there is another way to display these setups in the bank, let me know.

Searching `inv:TAG_NAME` and filtering based on this should be simple I think. This line [here](https://github.com/dillydill123/inventory-setups/blob/3102b4d1622885bad907077dee03b63a6b2184a4/src/main/java/inventorysetups/InventorySetupsPlugin.java#L488) needs to be replaced with some logic to check if a setup with the search specified exists (ignoring case or spaces, etc). This would allow it to work for both searches and when an inventory is being viewed. However, from developing this plugin I can definitely say the filtering is really strange and unpredictable. There are a lot of bugs that came out of this. One example is "Withdraw-X" and "Deposit-X" would remove the filter. So some testing would definitely need to be done on this. But I don't see any big issues with this. One question I have is: if you search `inv:TAG_NAME`, should the panel view that setup?

I like the Show worn items button idea. I think what it would do is call `setCurrentInventorySetup` on the panel which takes care of everything else. So most of the work is just creating the menu entries and mapping that to the proper inventory setup (either by name, menu index, etc). I've never created new menu entries, but many plugins have done it so I'm confident it's possible. The main issue is what happens when there are too many setups. Should I have only `x` amount of setups on the worn items button? Should I create a chatbox to cycle through the setups? How many setups is too many? These are some of the questions to answer for this feature.

If you would like to try implementing this, go ahead! If I like it I'll merge it in, but I can't guarantee anything. So it's up to you to spend your time on it. Else I can look into this more and decide on how to solve this problem.

**Comment by Matsyir** [comment]
I appreciate the quick response!

I imagine searching `inv:TAG_NAME` not having any effect on the panel, only filtering the bank while searching. But for the menu entry it makes sense to do the whole thing.

Happy to hear that I could add that behavior with a function call, for the menu entry. I think we could just display all their setups and let it overflow (similar to how a menu entry will overflow if there's too many players/items in 1 area). We could add another option on each setup to hide/show the inventory setup from the menu entries. Or possibly, allowing them to "move" setups, to change their order and put more commonly used ones first.

I will give it a shot myself, but possibly only next weekend. Maybe this week, not sure.

**Comment by dillydill123** [comment]
Keep in mind if a search filter is active, there's some checks in the other parts of the plugin that attempt to keep the filter active. This is because a lot of things remove the filter, or accidentally re-filter (like clicking on another tab). Like I said, the filtering is finicky. I used a lot of the same work arounds for the filtering as bank tags. Some of these checks look for a selected inventory setup, so there could be issues with keeping the search persistent. I can't say for certain, but just giving you a heads up. Hopefully my code isn't that bad to read :)

**Comment by Matsyir** [comment]
I get what you're saying. TBH, if I can get the menu entry additions to work, I don't think I'd ever use the search functionality anyways, so to me that's not as important as the menu entry solution which sounds like it'd be easier to add anyways.

**Comment by dillydill123** [comment]
I think this feature is just about done. Doing some additional testing on the edge cases:

![image](https://user-images.githubusercontent.com/15637422/82506702-7ed43b80-9ace-11ea-9218-69adcff7a1b8.png)

So this is what happens when I'm on fixed mode. Around 32 setups the menu will overflow.

![image](https://user-images.githubusercontent.com/15637422/82506765-acb98000-9ace-11ea-91d4-720d2a6034e9.png)

As you can see, you can move entries up and down and this will be reflected in the menu entries. It's definitely a bit tedious to move entries right now (the right click menus only allow you to move up one at a time), but at least it's possible. Maybe in the future I'll try to improve this aspect. But you can put the most commonly used setups at the top and these will show up.

I'm considering adding a menu entry that would remove the current setup and return to the overview panel. Would this be useful at all? There's already a hot key that can do this in the settings.

What do you think?

**Comment by Matsyir** [comment]
Very happy to see that you're making progress with this! Sorry I couldn't offer help sooner. It looks great to me (visually, haven't looked at the code, but if it works - it works).

Moving entries up one at a time should be fine, it shouldn't be something you have to do too often, it's exactly the functionality I had in mind if I was going to implement it. Yeah it's a little tedious but not too bad, much better than nothing. I know the space is restricted, but if you can find a way, it would make it a bit easier if it was just a button rather than a right click menu (this button wouldn't be grouped with the core config buttons, ideally).

I think the menu entry to clear would be useful, I often end up playing very casually, mostly using 1 hand. I would definitely use it.

I'm not sure if you restricted it to 32 rows due to your testing, but if you did, keep in mind resizeable users will be able to fit more on screen, it will be a very high number if they're playing for example in 4k without UI scaling (very unlikely though, practically unplayable).

Looking forward to using this, will be very convenient 😄

**Comment by dillydill123** [comment]
Yeah I've thought about adding arrow buttons but to be honest it's not much better because you would have to move the mouse to the arrow buttons every time if you want to move one panel a lot. This is definitely something i'd like to improve but don't have any good ideas at the moment. I'm hesitant to make the panels taller and add a new row of buttons. The best solution is drag and drop but this is a whole lot of work that I have no experience in, and the gain is not massive in my opinion.

Nothing in my plugin opens or closes the panel. So actually the default behavior is that the panel doesn't change. This means that if you selected a setup that doesn't have bank filtering and the panel is closed, it would look like nothing happened.  Same thing with the close setup option.

I added 32 setups (numbered 1-32) and saw the limit in fixed mode. In resizeable it can fit many more entries, so the 32 was not a restriction on my part. I just let the menus overflow on their own.

Here is the final product:

![image](https://user-images.githubusercontent.com/15637422/82611989-cbcc1680-9b8f-11ea-8485-f15b69f70e79.png)

**Comment by dillydill123** [comment]
It's been merged into the plugin hub

**Comment by Matsyir** [comment]
Understandable about the arrow button. I agree it's best to avoid adding more height to the panels as much as possible. Agreed about draggable, would be nice but probably way too much work for what it's worth, shouldn't have to move them very often.

Ah, my bad on the assumption, that's convenient.

I don't mind the open setup button, plenty of horizontal space to spare.

Just tried it quickly, looks very nice. So smooth and easy to use, love it!! It's even better than I imagined. I see what you mean that a button might even be harder than the right click menu, to move up/down. Should be fine as is.
