### ISSUE TITLE
Ban doesnt filter when i switch to another tab

### ISSUE THREAD

**Issue by oeg91** [dillydill123/inventory-setups#51]
Before today's update, i just needed to click in the **"show worn items"** in the bank, then click it again to close the interface and the bank got filter again, but it doesnt work now so i need to click in **"return to setups"** in the plugin, and choose the setup again so the bank shows the items in my setup. Closing and open the bank doesnt make it to filter again.
Is this intended?

**Comment by dillydill123** [comment]
The bank not filtering when opening was an oversight on my part. I’ve fixed that and should be available now. As for the “show worn items” clicking back will only filter if you haven’t clicked a different tab or search previously. I think this is better because it won’t filter once you’ve deactivated the filter by clicking a tab or search. 

By the way, you can add a key rebind in the config to refilter the bank. You could also right click the show worn items button and click on the setup you want to filter. Perhaps I can add a refilter button in the view setup panel as well?

**Comment by oeg91** [comment]
Thanks now is working great. I didnt notice about the hotkey before.
