### ISSUE TITLE
Suggestion: Filter for equipment only

### ISSUE THREAD

**Issue by asherbasher** [dillydill123/inventory-setups#59]
Would be nice to have a button when viewing a setup that allows you to filter for only the equipment section so you can quickly grab all the stuff you need to equip, then go back to the full setup with the inventory items. Perhaps even a button that toggles between all/inventory only/equipment only, or a setting which allows you to choose which behaviour you prefer.

The way to achieve this currently is by making two separate setups; one specifically for the items you need to equip and one specifically for the inventory but I think this could be streamlined.

**Comment by dillydill123** [comment]
I actually like this idea. But some of the details need to be fleshed out.

One: I could make the filter button cycle through the different options. This seems a bit annoying because you have to go to the side panel to change it from equipment to inventory a lot. But it would allow for default behaviors

Two: I could make an additional menu option somewhere in the bank to do this? I was thinking the "Show worn items" which already displays all setups. Maybe if a setup is selected it can have additional options which be used to choose the inventory or equipment when right clicked. This doesn't allow for default behavior though.

What do you think?

**Comment by asherbasher** [comment]
Option two sounds cool yeah. Missing default behaviour wouldn't be a big deal I imagine.

**Comment by dillydill123** [comment]
![image](https://user-images.githubusercontent.com/15637422/102823687-62241d00-43a9-11eb-8eb6-62e777b30810.png)

Looking good so far. You can filter with inventory, equipment, or additional items. Currently the only way to trigger these is to use 3 new hot keys I added:

![image](https://user-images.githubusercontent.com/15637422/102824219-669d0580-43aa-11eb-9c8b-531a91485db8.png)

I'm still trying to decide the best way to add an in game way to activate these options.

Currently, the mode only persists while a setup is activated. For example, if you select a setup by clicking the eye or from the shown worn items button, it will filter **all** items. From here, you can hit one of the hot keys to filter equipment/invent/additional items. As long as the setup is active, it will always have that filtering mode enabled, even if you leave and come back to the bank. The only way to go back to all items is to hit the refilter all hotkey, or to reselect the setup by clicking the eye or from shown worn items, or by setting the filtering mode to to all items some other way which I have yet to add

**Comment by dillydill123** [comment]
Available now in 1.9
