### ISSUE TITLE
Bank shouldn't filter unless the Invent Setups plugin pane is the active one

### ISSUE THREAD

**Issue by hjdarnel** [dillydill123/inventory-setups#66]
There's oftentimes I'll use the plugin to gear up, and then switch over to a different RuneLite pane (like hiscores), and then when I end up back at the bank it's still in the "Search" mode for that setup. I think it'd be great if that filtering feature only applied when the pane is visible. Thanks for your work!

**Comment by dillydill123** [comment]
Hey, sorry for taking a while to comment on this. I think I can make this a config option because I know some people like this setting but I can understand your concern. One question, do you think activating the Inventory Setups pane should cause filtering to occur if you are browsing the bank?

**Comment by hjdarnel** [comment]
I think that would be reasonable @dillydill123 

Basically if I have the plugin open and a loadout selected, I'll be expecting my bank to be filtered! Otherwise it'll be surprising me (it seems to be active in the background)

**Comment by dillydill123** [comment]
![image](https://user-images.githubusercontent.com/15637422/102813699-4748ad00-4397-11eb-9a89-a3e388f772f5.png)

Here is the config option. If this is checked, the plugin will require the Inventory Setups pane to be active in order to filter. If the bank is not filtered, clicking on the pane when a setup is selected will cause a filter. Currently, if you open the bank with the pane active and it filters, clicking a different pane **will not** remove the filter. I think this is the better option, rather than canceling the filter.

This will be in the next release.

**Comment by dillydill123** [comment]
Available now in 1.9
