### ISSUE TITLE
Add ability to move panels up or down the list

### ISSUE THREAD

**Issue by dillydill123** [dillydill123/inventory-setups#7]
Add a way to move panels up and down so players can order their setups to their liking. 

Should this be drag and drop? Should right click menus be added? Should arrow buttons be added? Space is becoming limited on the panels for buttons. Drag and drop seems complicated for no substantial benefit.

**Comment by asherbasher** [comment]
From a user perspective, drag and drop seems like the best implementation. Although I would prefer it to follow the insert method of drag and drop, so that it goes in between setups rather than directly swapping. The way the RuneLite bank tag tabs are only able to be swapped instead of inserted is a small grievance I have.

Can't speak on your comment about the difficulty as I'm not a developer.

**Comment by asherbasher** [comment]
From a user perspective, drag and drop seems like the best implementation. Although I would prefer it to follow the insert method of drag and drop, so that it goes in between setups rather than directly swapping. The way the RuneLite bank tag tabs are only able to be swapped instead of inserted is a small grievance I have, although there was a workaround added for that.

Can't speak on your comment about the difficulty as I'm not a developer.

**Comment by dillydill123** [comment]
I’m going to go with a right click menu to move the setups up and down for now. Drag and drop is quite complicated and I’m unsure if it’s worth the effort

**Comment by dillydill123** [comment]
Implemented and merged. Can look into another solution because the current one isn't the best. But at least there's some way to move them at the moment.
