### ISSUE TITLE
Dragonfire shield placeholder disappears when withdrawn from bank 

### ISSUE THREAD

**Issue by xlrc** [dillydill123/inventory-setups#71]
Dragonfire shield placeholder disappears when withdrawn from bank. Not major but I thought I'd point it out. Thanks

**Comment by dillydill123** [comment]
This is probably occurring because of the new fuzzy system defaulting to off and the fact that the dragon fire shield has different variants when it is charged vs uncharged. Can you try right clicking the slot with the DFS and selecting "Toggle Fuzzy" and see if the place holder appears in the bank?

**Comment by xlrc** [comment]
That did in fact fix it it by setting to fuzzy. It looks like its showing the placeholder as an uncharged variant in the back when withdrawn as you said
![image](https://user-images.githubusercontent.com/76565981/103159667-12d45700-47c4-11eb-82a9-8b0c65df9f3d.png)

**Comment by dillydill123** [comment]
Yep, this is actually how it is always worked, it's just that with the new fuzzy system, the default is off, which is opposite how it worked before. I made this change because extra items were showing up when users did not want them to.
