### ISSUE TITLE
Add user-defined pattern matching or fuzzy but nonzero option for slots

### ISSUE THREAD

**Issue by nickbeckwith** [dillydill123/inventory-setups#84]
Would be great if an inventory slot could only match with charged amulet of glorys for example. I can think of two ways users could interact with this, ignoring plausibility:

* Allow a slot to match against a pattern, ideally more versatile than the bank tabs * fuzzy specifier. You specify the pattern in some setting. The right click context menu of a slot would contain `Match Patterns->{user patterns here}` along with the preexisting context menu options.
* Allow a fuzzy but nonzero option that only matches charged jewelry, not fully-degraded barrows items etc. This would be in the context menu of a slot under the fuzzy option.
* Edit: Is this something we could use the "stack filtering" option or something similar and extend it to potions, degradable items and jewelry?

I have a feeling the implementation is limited by the bank tags implementation. If that's the case, let me know, and I can make the suggestion there first, and you all (or I) can build off here.

**Comment by nickbeckwith** [comment]
Another implementation that is probably the most intuitive for end users is to be able to match with tags similar to how you can search for tags in bank tags. Allow the following e.g.
Update Slot From Search -> tag::charged_glory

It is up to the user to populate the charged_glory tag. There's already helpful tag imports anyway.

**Comment by dillydill123** [comment]
I'm a bit limited in how the fuzzy filtering works, because I actually use the RuneLite ItemVariation Mapping API. So stuff like fuzzy but nonzero or using stack filtering would be entirely on me to implement, which I'm not interested in due to the time and scalability (would need to be updated every time new items are in).

As far as a user-defined pattern matching, I think it's technically possible to allow something like this. Currently, all comparisons for highlighting purposes are done with Item IDs instead of names. I chose this option because of speed (no need for string comparisons) and simplicity. In fact, Inventory Setups doesn't even retrieve names of items from the RuneLite API when it fetches the current inventory and equipment for highlight comparison. That would need to be run on the client thread. There are a few obstacles I see with changing this:

- Using strings will significantly increase the cost of highlighting. Perhaps one way to avoid this is to only use string matching when a pattern is given in a slot. But if the patterns are to be used in bank filtering as well, this will add a huge amount of runtime. Bank filtering only compares IDs at the moment.
- The config which saves all inventory setups will become really large. It's already quite hefty and adding a list for every slot for patterns will make them even bigger. One possibility is to see If I can have no list (which would equate to null) when saving/loading the config.
- Unordered highlighting becomes even weirder with patterns. What if multiple match, which should item be given priority?

As of right now, I think this is technically possible. I'm just unsure of the feasibility, or if it's worth while. The main use case I can see is things like removing uncharged glories or fully degraded barrows items showing up in the bank filter. If a user wants an additional item in the bank filter, they can use additional filtered items to accomplish this. I think an easier solution would be something like a blacklist, but even this doesn't seem super useful given the implementation cost.

**Comment by nickbeckwith** [comment]
Appreciate the response. After reading that and also taking a look at the source code, I agree that the implementation cost is maybe just a little too high for the limited use cases. I was expecting some pre-existing solutions. Given that, I'll close it. Maybe we can reopen when someone else implements it:)

**Comment by dillydill123** [comment]
Sounds good. Thank you for the suggestion nonetheless.
