### ISSUE TITLE
Tab layouts and/or tag exporting

### ISSUE THREAD

**Issue by hctim852** [dillydill123/inventory-setups#85]
With the recent popularity of the Bank Tab Layouts plugin, it really makes me wish that the equipment setups sorting (equipment/inventory) supported layouting as well. If that's not possible to integrate, could you add a feature to be able to export your equipment/inventory/rune pouch/additional items to be able to import them as a bank tab? Let me know if that makes sense or if its even possible.

Thanks,

**Comment by dillydill123** [comment]
Do you mean have a separate layout when equipment/inventory is filtered? I've spoken with geheur (creator of the Bank Tab Layouts plugin) and we don't think this is particularly useful, because you can just organize the layout how u want it with all items.

btw, make sure you have bank-tag-layouts v1.3, because the it will have the layout available when filtering equipment/inventory.

**Comment by hctim852** [comment]
Actually, sorry, what I'm requesting is already a feature, I just hadn't updated! Non need to have different layouts for equipment/inventory separately. Thanks for all your hard work on this, one of my favorite plugins by far!
