### ISSUE TITLE
Dragonfire Ward Placeholder Disappears

### ISSUE THREAD

**Issue by Chuncster** [dillydill123/inventory-setups#90]
Inventory setup using the Dragonfire Ward, when getting the items out of the bank everything creates placeholders but the dragonfire ward disappears from the setup. A placeholder remains in the normal bank but when on the Inventory Setup bank tab it isn't there.

**Comment by dillydill123** [comment]
I think this because the placeholder for the dragonfire ward is actually the uncharged version of the shield. There are a few items that act similarly like this. I can't make it a default to automatically show these in the bank, because then sometimes undesirable items would show up (like different potion doses, jewelry charges, etc). So the only way to solve this would be to set the slot with the dragonfire ward to Fuzzy. The placeholder should show up in the bank then.

**Comment by dillydill123** [comment]
I'm going to close this. Please reopen if you still aren't seeing the placeholder after making it fuzzy.
