### ISSUE TITLE
Setups Reset On Restart

### ISSUE THREAD

**Issue by TheFortuneCat** [dillydill123/inventory-setups#98]
Everytime I restart Runelite my inventory setups rollback to how they were around 3 months ago.

**Comment by dillydill123** [comment]
Hey, are your setups saved to the cloud in a RuneLite account as well as locally? You might have different setups locally vs online.

**Comment by TheFortuneCat** [comment]
I've looked through the readme as well as all the options in game and do not see any options for how things are saved, but this does sound like my issue.

**Comment by robbrown92** [comment]
im having this problem too, setup 4 different groups and they all reset

**Comment by dillydill123** [comment]
If you have steps to reproduce it would be really helpful

**Comment by rbbi** [comment]
Example case:

Two RuneLite clients are running at the same time - client 1 and client 2. This is a very common scenario as many players will play multiple accounts at the same time.

Client 1 adds a new inventory setup, the inventorySetups are serialized to JSON and saved on the local machine.
Client 2 then adds a new inventory setup. Because client 2 hasn't refreshed to see the new config added by client 1, when the inventory setup is saved it overwrites the new setup created by Client 1 - losing it.

Fix: Re-read the config first before updating it to ensure that the client is synchronized with the latest data, or append to the inventory setups file when adding a new setup instead of overwriting

**Comment by dillydill123** [comment]
If I understand correctly, this happens only if the two clients are using local data or logged into the same account right?

**Comment by rbbi** [comment]
In my case, I had two clients both logged into the same RuneLite cloud account.

**Comment by dillydill123** [comment]
I've spoken with adam about this and having two clients using the same session file is not really a good idea. I would recommend using separate runelite accounts for different osrs accounts. Even if you log out and log in with a different runelite account it can cause weird behavior. So the recommended method is to launch runelite with session files:

```
start "" C:\Users\Dillon\AppData\Local\RuneLite\RuneLite.exe --clientargs "--sessionfile=C:\Users\Dillon\.runelite\profiles\acc1@gmail.com\session"
start "" C:\Users\Dillon\AppData\Local\RuneLite\RuneLite.exe --clientargs "--sessionfile=C:\Users\Dillon\.runelite\profiles\acc2@gmail.com\session"
start "" C:\Users\Dillon\AppData\Local\RuneLite\RuneLite.exe --clientargs "--sessionfile=C:\Users\Dillon\.runelite\profiles\acc3@gmail.com\session"
```

For example I played on 3 accounts at one point and used a batch script to launch my RuneLite accounts like so. See https://github.com/runelite/runelite/wiki/General-Features#playing-with-multiple-accounts for more details
